version: '3.8'

x-env: &commonEnv
  LEADER: node1
  LEVEL_DEBUG: true

x-depon: &commonDepon
  - node1

x-build: &commonBuild
  context: .
  dockerfile: Dockerfile


services:
  node1:
    build:
      <<: *commonBuild
    environment:
      NODE_ID: node1
      PEERS: node2:50051,node3:50051
      <<: *commonEnv
    ports:
      - "50051:50051"
    volumes:
      - node1_data:/app/data
    # depends_on: *commonDepon # comment because this node is leader, will make error `dependency cycle detected`
    restart: on-failure:3

  node2:
    build:
      <<: *commonBuild
    environment:
      NODE_ID: node2
      PEERS: node1:50051,node3:50051
      <<: *commonEnv
    ports:
      - "50052:50051"
    volumes:
      - node2_data:/app/data
    depends_on: *commonDepon
    restart: on-failure:3

  node3:
    build:
      <<: *commonBuild
    environment:
      NODE_ID: node3
      PEERS: node1:50051,node2:50051
      <<: *commonEnv
    ports:
      - "50053:50051"
    volumes:
      - node3_data:/app/data
    depends_on: *commonDepon
    restart: on-failure:3

volumes:
  node1_data:
  node2_data:
  node3_data: